<a href="https://colab.research.google.com/github/mia-readowrite/hii_demo/blob/master/my_python_google_collab_nbk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world!")

hello world!


okay so let's see how numpy library works in python

In [3]:
#importing numpy library with a nickname np
import numpy as np  # numpy is a library containing many packages. packages are collection of modules.
import time # time is a module containing time related functions. math is also a module as in math.sqrt

x = np.random.rand(100000)
start = time.time()
print (start)
#now let's do some calculaion where we find te mean of these instance of time

1653840728.2472944


In [15]:
mean = sum(x)/len(x) #since mean = total of all elements/no. of elements
print (mean)
print(time.time()-start)

0.5004645378823235
179.48153042793274


In [16]:
#let's do the same question using numpy attributes
start = time.time()
mean_numpy = np.mean(x)
print (time.time()-start)


0.0005137920379638672


let's learn how to create numpy arrays

In [32]:
a = np.array(["hello",'world'])
print(a,"\n", type(a)) # this will print the vaalue in array 'A' as well as the type of array

print(a.ndim)# this prints the dimensiom of array "a". note that "n" in "ndim " or "ndarray" reperesents "N-Dimensional array"



['hello' 'world'] 
 <class 'numpy.ndarray'>
1


In [63]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b,"\n\n", b.ndim,"\n"*2, type(b), "\n"*2, b.shape,"   - this tells the dimension (rows x columns)")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 2 

 <class 'numpy.ndarray'> 

 (3, 3)    - this tells the dimension (rows x columns)


In [67]:
#you'd be surprised to know that we can do all soughts of operations on this arra. let's take array b for this
print(b+10,"\n")
print(b-10,"\n")
print(b*2,"\n")
print(b/10,"\n")
# NOTE : these are all TEMPERORY Values 

[[11 12 13]
 [14 15 16]
 [17 18 19]] 

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]] 



In [70]:
#lets now see permanent change in the value of b 
b = b+10
print(b)

[[31 32 33]
 [34 35 36]
 [37 38 39]]


___
Let's view some more operations:
namely:---

***max, min, floor, ceil, mean, copy and view*** . they somewhat resemble pass by value and pass by reference.

In [86]:
from numpy.lib.function_base import copy
x=np.array([1,2,3,4,5,6])
print(np.max(x))
print(np.min(x))

print(np.mean(x))

print(np.floor(x),"prints floor value") 
print(np.ceil(x),"prints ceil value")

6
1
3.5
[1. 2. 3. 4. 5. 6.] prints floor value
[1. 2. 3. 4. 5. 6.] prints ceil value


In [87]:
#copy function
x1= x.copy()
print ("prints copy array value--",x1,"\n","prints original value--",x,"\n"*2)
x1[2]=40
print ("prints copy array value--",x1,"\n","prints original value--",x)

prints copy array value-- [1 2 3 4 5 6] 
 prints original value-- [1 2 3 4 5 6] 


prints copy array value-- [ 1  2 40  4  5  6] 
 prints original value-- [1 2 3 4 5 6]


In [88]:
#view function
x2= x.view()
print ("prints view array value--",x2,"\n","prints original value--",x,"\n"*2)
x2[1]=40
print ("prints view array value--",x2,"\n","prints original value--",x)

prints view array value-- [1 2 3 4 5 6] 
 prints original value-- [1 2 3 4 5 6] 


prints view array value-- [ 1 40  3  4  5  6] 
 prints original value-- [ 1 40  3  4  5  6]
